### ISSUE TITLE
Push e pull

### ISSUE THREAD

**Issue by abdulmeque** [joadourajoaqu/AndroidAppClient-Emprego#1]
Eu ja expliquei sobre isso de fazer upload pelo browser.... o repositorio eh pra guardar o projecto, na forma original. usem a git do command-line pra carregar projectos ou pasta que contem o projecto pro repositorio. o github nao eh plataforma para submeter trabalhos nao. por favor.

**Comment by joadourajoaqu** [comment]
Entendido docente, ja foi resolvido.

**Comment by abdulmeque** [comment]
Finalmente. bom trabalho
